steps:
- name: 'python:3-alpine'
  args: ['pip','install','-r','requirements.txt']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'eu.gcr.io/advise-inno-host/hello-kube:$SHORT_SHA', 'app']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'eu.gcr.io/advise-inno-host/hello-kube:$SHORT_SHA']
images: ['eu.gcr.io/advise-inno-host/hello-kube']
