---
apiVersion: v1
kind: Pod
metadata:
  name: pod-hello-kubernetes
spec:
  containers:
  - name: hello-kubernetes
<<<<<<< HEAD
    image: #
=======
    image: eu.gcr.io/fourcast-gke-demo/hello-kube:0.2
>>>>>>> develop
    ports:
    - containerPort: 5000