---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: deploy-hello-kubernetes
spec:
  template:
    metadata:
      labels:
        app: pod-hello-kubernetes
    spec:
      containers:
      - name: hello-kubernetes
<<<<<<< HEAD
        image: #
=======
        image: eu.gcr.io/fourcast-gke-demo/hello-kube:0.2
        imagePullPolicy: Always
>>>>>>> develop
        resources:
          limits:
            cpu: "0.1"
            memory: 100Mi
        livenessProbe:
          httpGet:
            path: #
            port: 5000
        readinessProbe:
          httpGet:
            path: #
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP

        ports:
        - name: http-api
          containerPort: 5000