---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-hello-kubernetes
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: deploy-hello-kubernetes
  minReplicas: 1
  maxReplicas: 1000
  targetCPUUtilizationPercentage: 10
